jwt:
  secret: 2345ho2j4h523j23j45l23k4
  lifetime: 30m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ens
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
